### ISSUE TITLE
Generator annotations are not interpreted according to PEP 484

### ISSUE THREAD

**Issue by mihaic** [agronholm/typeguard#15]
Try this example:

```python
from typing import Generator, no_type_check
from warnings import filterwarnings

from typeguard import TypeChecker, TypeWarning


def generator_example() -> Generator[int, None, None]:
    for i in range(3):
        yield i


def main() -> None:
    filterwarnings("error", category=TypeWarning)
    checker = TypeChecker("__main__")
    checker.start()
    results = generator_example()
    for result in results:
        print(result)


if __name__ == "__main__":
    main()
```

I get:
```typeguard.TypeWarning: [MainThread] return from __main__.generator_example() at generator_fail.py:9: type of the return value must be collections.abc.Generator; got int instead```

As a workaround, I decorate generators with `@no_type_check`.

**Comment by agronholm** [comment]
Seems like "yield" is handled as a return. This indeed has to be taken into account. I hope it's possible to implement.

**Comment by jolaf** [comment]
This looks like a really critical problem, taking into account the amount of asynchronous code around now.

The same problem occurs with `Iterator` return type annotations.

**Comment by agronholm** [comment]
Not sure how critical this is as I've never seen code in the wild that uses both typeguard and annotated generator functions together. But I'll see what I can do.

**Comment by jolaf** [comment]
Well I work for a company that's thinking of using `typeguard` to improve its annotated code, but we have a lot of generators there.

Thank you very much!

**Comment by agronholm** [comment]
I don't think it's possible to support type checking generators (async or not) using the profiler approach. I just checked and at no point is the generator object made visible to the type checker. Uses of the generator are detected, however, but it's impossible to make a connection between a function annotation and the actual generator object. The best I could do check if the function is a generator (async or otherwise) and disable type checking for it if it is.

**Comment by jolaf** [comment]
The current error diagnostic shows that the type of value veing `yield` is visible as well as the fact that the method is `Generator`.

Isn't it possible to extract from `Generator` the type of value it is expected to `yield`?

**Comment by jolaf** [comment]
Disabling type checking for return values of generators/coroutines looks like a reasonable fallback.

**Comment by agronholm** [comment]
> Isn't it possible to extract from Generator the type of value it is expected to yield?

Sure it is. I initially didn't know how to connect the yield operation to the originating function, but it is indeed possible because the yield shows up as a `return` with the yielded value as the return value. This makes it possible to type check the yields which is not possible with either of the other operating modes. Paradoxically it is not possible to get the actual generator object from the initial call to the generator function. Also it is possible to detect calls to the generator's `send` method but the value is not visible to the profiler hook.

**Comment by agronholm** [comment]
Thinking more clearly about this, it was precisely because the yields show up as returns that this issue exists to begin with. I will work on this some more after a good night's sleep.

**Comment by agronholm** [comment]
Ok so I've been digging deeper into this. For regular generators, type checking via the profiler hook is possible but not so for async generators because the return value is wrapped inside an opaque, undocumented built-in object of type `async_generator_wrapped_value` and there is no way to get the actual value from that.

**Comment by jolaf** [comment]
Cool, thanks!

**Comment by jolaf** [comment]
It seems this issue is still actual, see #77.

**Comment by agronholm** [comment]
The example snippet at the top does not give any errors, so I am not reopening this. The referred issue is due to an annotated type other than `Generator` being used.
