### ISSUE TITLE
AttributeError: 'xxxx' object has no attribute '__code__'

### ISSUE THREAD

**Issue by epenet** [agronholm/typeguard#191]
**Describe the bug**
When using https://github.com/pallets/click, the `@click.group()` function decorator return a class instance (`click.core.<Group xyz>`) which does not have associated code. This causes Typeguard to fail with `AttributeError: 'Group' object has no attribute '__code__'`.

**To Reproduce**
Failure can be seen on https://github.com/hacf-fr/renault-api/runs/2664117342.
I'm working on a smaller reproducible example

**Expected behavior**
Should pass

**Additional context**
https://github.com/pallets/click/issues/1927

**Comment by epenet** [comment]
I think the issue is that the `@click.group()` decorator effectively replaces a function (`xxx`) with a class instance and an associated callback (`<Group xxx>`)

Is it an issue with the pytest plugin? with the import hook?
I tried to add `@typeguard_ignore` but it didn't change a thing.

Note: I use the pytest plugin with `pytest --typeguard-packages=renault_api`

**Comment by cjolowicz** [comment]
@agronholm I can confirm that #190 fixes this.

Here's a failing test to demonstrate the issue:

```python
# tests/test_typeguard.py
class TestTypeChecker:
    ...
    def test_callable(self):
        class command:
            # we need an __annotations__ attribute to trigger the code path
            whatever: float

            def __init__(self, function: Callable[[int], int]):
                self.function = function

            def __call__(self, arg: int) -> None:
                self.function(arg)

        @typechecked
        @command
        def function(arg: int) -> None:
            pass

        function(1)
```

@epenet Feel free to include this in your PR.

Some additional info:

- This bug is triggered by click >= 8.0 because `click.Command` now has an `__annotations__` attribute. Before, typeguard would just bail out with a warning because this attribute was missing from the callable.
- Typeguard's import hook inspects the AST to find function definitions that should be instrumented. So it considers a function decorated by `@click.command` fair game. It will then use [inspect.unwrap](https://docs.python.org/3/library/inspect.html#inspect.unwrap) to get to a function with a `__code__` attribute. However, click does not set the `__wrapped__` attribute on `click.Command` instances, so unwrapping leads nowhere.
- The click maintainer has previously rejected using [functools.wraps](https://docs.python.org/3.10/library/functools.html#functools.wraps) for click's decorators (https://github.com/pallets/click/issues/1472#issuecomment-673698763). In fact, the type signature of the callable is quite different from that of the wrapped function. So this would not be a solution and would produce a false positive in Typeguard.
- In the long run it would be great if Typeguard were able to type-check callables (#84). But meanwhile #190 seems like a good solution.

**Comment by cjolowicz** [comment]
Here's a temporary workaround for the issue:

```python
try:
    import typeguard  # type: ignore[import]
except ImportError:
    pass
else:  # pragma: no cover
    from typing import no_type_check

    @no_type_check
    def _patched_typechecked(*args, **kwargs):
        if args and isinstance(args[0], click.Command):
            return args[0]
        return typeguard_typechecked(*args, **kwargs)

    typeguard_typechecked = typeguard.typechecked
    typeguard.typechecked = _patched_typechecked
```

Not exactly beautiful... I literally found no better way to do this :disappointed:

**Comment by epenet** [comment]
Thanks @cjolowicz I've updated the PR
