### ISSUE TITLE
typechecked not compatible with class property decorator

### ISSUE THREAD

**Issue by Jonas1312** [agronholm/typeguard#355]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4

Bug is not present with typeguard v2

### Python version

3.7

### What happened?

The code below raises:

```text
    obj.a = "2"
TypeError: a() takes 1 positional argument but 2 were given
```

### How can we reproduce the bug?

```python
from typeguard import typechecked


class MyClass:
    def __init__(self) -> None:
        self._a = "1"

    @property
    def a(self) -> str:
        return self._a

    @a.setter
    @typechecked
    def a(self, a: str) -> None:
        self._a = a


obj = MyClass()
print(obj.a)
obj.a = "2"
print(obj.a)

```

**Comment by agronholm** [comment]
It appears that this is caused by the fact that `@typechecked` looks up the target function based on the fully qualified name, which would be the same for both the getter and the setter. The fix would be to improve the accuracy of the targeting by specifying the target line number as well. The only workarounds I can think of right now are to either use the import hook or `check_type()` instead.

**Comment by agronholm** [comment]
I'm finally making some progress with this. It can be reproduced w/o getters/setters, like this:
```python
from typeguard import typechecked


@typechecked
def func(value: int) -> None:
    print("first")

first_func = func

@typechecked
def func(value: int) -> None:
    print("second")

first_func(1)
func(1)
```
The above code prints `first` twice. Once I figure out why it's replacing the second function with the code of the first, I can fix this.
