### ISSUE TITLE
Conda packaging

### ISSUE THREAD

**Issue by itamarst** [agronholm/typeguard#56]
I'm about to open a PR for conda-forge packaging of `typeguard`. It would be useful if you were a maintainer as well, so you can updates conda packages as soon as there is a new release. Any problems with adding you as maintainer?

**Comment by itamarst** [comment]
The infrastructure for conda-forge is highly automated, so maintenance seems pretty low burden.

**Comment by agronholm** [comment]
My goal is to actually deprecate typeguard in favor of pytypes at some point.
What actions are needed on my behalf for this?

**Comment by agronholm** [comment]
Typeguard has become a significant time sink for me and there are other projects with very similar aims. I've met with Stewori face to face on a few occasions and agreed to cooperate with him on this. In fact, pytypes has integrated quite a few features directly from typeguard. So far I've had a number of reservations about pytypes, however, due to how invasive and ugly the code is (monkey patching on import among other things). Proper run time type checking is also a highly complex endeavor and no library does it even nearly perfectly.

**Comment by agronholm** [comment]
You can add me as a maintainer, but I make no promises.

**Comment by itamarst** [comment]
Well, as a user I'm very grateful for your work! Could you get pytypes to merge into typeguard, so you start with better codebase, and then you can maintain it together?

**Comment by Stewori** [comment]
The uglyness in parts of pytypes is not by choice. It is mainly due to aims for full compatibility with older versions of typing module (including Python 2.7), which underwent vast changes between versions. I never found the time to cover the newest breaking changes introduced with Python 3.7.
One of the monkeypatches is to fix a substantial bug in one version of typing shipped with Python 3.5.
In general, pytypes aims for a much higher feature set, which makes it far more complex. E.g. it supports stubfiles, has a typesafe override annotation and it predates pyannotate w.r.t. the introduction of annotations from runtime observations.

That said, it became a timesink for me too and I can currently not afford to spend time on it. That's why Python 3.7 support is lagging and code cleanup has low priority. Note that I actually do not need it for my own work at the moment so it does not pay off for me. I usually went on with maintenance but given the non-trivial Python 3.7 breakage and who knows what Python 3.8 will break again I cannot make promises at all.

**Comment by itamarst** [comment]
Just my two cents, but Python 2.7 is EOL'd in a year, so everyone is starting to drop support or port away. And it would seem like it would be lower effort if everyone focused on one project... 2-3 people barely doing maintenance on just one project will go a lot further.

So it would be nice if you could pick one and say "this is what everyone should use." And if that takes dropping some functionality, maintained small functionality is better than unmaintained large functionality.

**Comment by Stewori** [comment]
Python 2.7 compatibility is kept specifically for Jython support.
Actually, I think not Python 2.7 is the main burden, but the constant changes within typing, which equally affect Python 2.7 and 3.x. I guess that is a consequence of typing still being "provisional". It seems to me that maintaining any typing-related project is inherently inefficient while this is the case.

**Comment by itamarst** [comment]
Conda packages are now available: https://anaconda.org/conda-forge/typeguard

**Comment by Stewori** [comment]
@itamarst It looks like pytypes is already on conda forge as well: https://anaconda.org/conda-forge/pytypes
However I cannot remember that I was asked to become a maintainer of that package. Anyway, it looks like some mild maintenance would do good there:

- description is missing
- not the newest version (beta3 vs beta5)

Do you know how to act on this?
